/* Interface translations. Quote contents are always left exactly as the user entered them. */
const I18N={
 it:{dashboard:'Panoramica',quotes:'Preventivi',business:'La mia attività',newQuote:'Nuovo preventivo',recent:'Preventivi recenti',created:'Preventivi creati',sent:'Preventivi inviati',totalQuoted:'Totale preventivato',archive:'Archivio',settings:'Impostazioni',save:'Salva',download:'Scarica PDF',duplicate:'Duplica',delete:'Elimina',back:'Archivio',customer:'Cliente',items:'Voci',summary:'Riepilogo',tax:'Imposte',language:'Lingua',currency:'Valuta',country:'Paese',taxProfile:'Profilo fiscale',manualTax:'Aliquota predefinita',draft:'Bozza',sentStatus:'Inviato',accepted:'Accettato',rejected:'Rifiutato'},
 en:{dashboard:'Dashboard',quotes:'Quotes',business:'My business',newQuote:'New quote',recent:'Recent quotes',created:'Quotes created',sent:'Quotes sent',totalQuoted:'Quoted total',archive:'Archive',settings:'Settings',save:'Save',download:'Download PDF',duplicate:'Duplicate',delete:'Delete',back:'Archive',customer:'Customer',items:'Items',summary:'Summary',tax:'Taxes',language:'Language',currency:'Currency',country:'Country',taxProfile:'Tax profile',manualTax:'Default tax rate',draft:'Draft',sentStatus:'Sent',accepted:'Accepted',rejected:'Rejected'},
 es:{dashboard:'Resumen',quotes:'Presupuestos',business:'Mi empresa',newQuote:'Nuevo presupuesto',recent:'Presupuestos recientes',created:'Presupuestos creados',sent:'Presupuestos enviados',totalQuoted:'Total presupuestado',archive:'Archivo',settings:'Ajustes',save:'Guardar',download:'Descargar PDF',duplicate:'Duplicar',delete:'Eliminar',back:'Archivo',customer:'Cliente',items:'Conceptos',summary:'Resumen',tax:'Impuestos',language:'Idioma',currency:'Moneda',country:'País',taxProfile:'Perfil fiscal',manualTax:'Tipo predeterminado',draft:'Borrador',sentStatus:'Enviado',accepted:'Aceptado',rejected:'Rechazado'},
 fr:{dashboard:'Tableau de bord',quotes:'Devis',business:'Mon entreprise',newQuote:'Nouveau devis',recent:'Devis récents',created:'Devis créés',sent:'Devis envoyés',totalQuoted:'Total devisé',archive:'Archives',settings:'Paramètres',save:'Enregistrer',download:'Télécharger le PDF',duplicate:'Dupliquer',delete:'Supprimer',back:'Archives',customer:'Client',items:'Lignes',summary:'Récapitulatif',tax:'Taxes',language:'Langue',currency:'Devise',country:'Pays',taxProfile:'Profil fiscal',manualTax:'Taux par défaut',draft:'Brouillon',sentStatus:'Envoyé',accepted:'Accepté',rejected:'Refusé'},
 de:{dashboard:'Übersicht',quotes:'Angebote',business:'Mein Unternehmen',newQuote:'Neues Angebot',recent:'Letzte Angebote',created:'Angebote erstellt',sent:'Angebote gesendet',totalQuoted:'Angebotssumme',archive:'Archiv',settings:'Einstellungen',save:'Speichern',download:'PDF herunterladen',duplicate:'Duplizieren',delete:'Löschen',back:'Archiv',customer:'Kunde',items:'Positionen',summary:'Übersicht',tax:'Steuern',language:'Sprache',currency:'Währung',country:'Land',taxProfile:'Steuerprofil',manualTax:'Standard-Steuersatz',draft:'Entwurf',sentStatus:'Gesendet',accepted:'Akzeptiert',rejected:'Abgelehnt'},
 pt:{dashboard:'Painel',quotes:'Orçamentos',business:'Minha empresa',newQuote:'Novo orçamento',recent:'Orçamentos recentes',created:'Orçamentos criados',sent:'Orçamentos enviados',totalQuoted:'Total orçado',archive:'Arquivo',settings:'Configurações',save:'Guardar',download:'Baixar PDF',duplicate:'Duplicar',delete:'Excluir',back:'Arquivo',customer:'Cliente',items:'Itens',summary:'Resumo',tax:'Impostos',language:'Idioma',currency:'Moeda',country:'País',taxProfile:'Perfil fiscal',manualTax:'Taxa padrão',draft:'Rascunho',sentStatus:'Enviado',accepted:'Aceito',rejected:'Recusado'},
 ar:{dashboard:'لوحة التحكم',quotes:'عروض الأسعار',business:'نشاطي',newQuote:'عرض سعر جديد',recent:'العروض الأخيرة',created:'العروض المنشأة',sent:'العروض المرسلة',totalQuoted:'إجمالي العروض',archive:'الأرشيف',settings:'الإعدادات',save:'حفظ',download:'تنزيل PDF',duplicate:'نسخ',delete:'حذف',back:'الأرشيف',customer:'العميل',items:'البنود',summary:'الملخص',tax:'الضرائب',language:'اللغة',currency:'العملة',country:'الدولة',taxProfile:'الملف الضريبي',manualTax:'معدل افتراضي',draft:'مسودة',sentStatus:'مرسل',accepted:'مقبول',rejected:'مرفوض'},
 ja:{dashboard:'ダッシュボード',quotes:'見積書',business:'事業者情報',newQuote:'新しい見積書',recent:'最近の見積書',created:'作成済み',sent:'送信済み',totalQuoted:'見積合計',archive:'アーカイブ',settings:'設定',save:'保存',download:'PDFをダウンロード',duplicate:'複製',delete:'削除',back:'アーカイブ',customer:'顧客',items:'明細',summary:'合計',tax:'税金',language:'言語',currency:'通貨',country:'国',taxProfile:'税務プロファイル',manualTax:'標準税率',draft:'下書き',sentStatus:'送信済み',accepted:'承認済み',rejected:'却下'},
 zh:{dashboard:'概览',quotes:'报价单',business:'我的企业',newQuote:'新建报价单',recent:'最近报价单',created:'已创建报价单',sent:'已发送报价单',totalQuoted:'报价总额',archive:'档案',settings:'设置',save:'保存',download:'下载 PDF',duplicate:'复制',delete:'删除',back:'档案',customer:'客户',items:'项目',summary:'汇总',tax:'税务',language:'语言',currency:'货币',country:'国家/地区',taxProfile:'税务配置',manualTax:'默认税率',draft:'草稿',sentStatus:'已发送',accepted:'已接受',rejected:'已拒绝'}
};
